In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.1.0+cu121'

In [4]:
tsr = torch.randn(4,5)
tsr

tensor([[ 0.3351, -0.8894, -1.4380, -1.8493,  1.5518],
        [ 0.3086,  0.0354,  1.0588,  0.7706,  1.0180],
        [-0.2362,  1.9476, -0.6131, -0.8576,  0.4123],
        [ 2.6931,  0.1153,  1.6788,  0.2622,  0.9907]])

In [5]:
m = torch.max(tsr)
m

tensor(2.6931)

In [6]:
m = torch.min(tsr)
m

tensor(-1.8493)

In [7]:
m, idx = torch.max(tsr, 0)
print(m)
print(idx)

tensor([2.6931, 1.9476, 1.6788, 0.7706, 1.5518])
tensor([3, 2, 3, 1, 0])


In [8]:
m, idx = torch.max(tsr, dim=0)
print(m)
print(idx)


tensor([2.6931, 1.9476, 1.6788, 0.7706, 1.5518])
tensor([3, 2, 3, 1, 0])


In [9]:
p =(m, idx)
torch.max(tsr, 0, out=p)



torch.return_types.max_out(
values=tensor([2.6931, 1.9476, 1.6788, 0.7706, 1.5518]),
indices=tensor([3, 2, 3, 1, 0]))

In [10]:
# 創建一個 2x3 的零矩陣
tensor1 = torch.zeros(2, 3)
print("零矩陣:")
print(tensor1)

# 創建一個 2x3 的隨機矩陣
tensor2 = torch.rand(2, 3)
print("\n隨機矩陣:")
print(tensor2)

# 創建一個直接由數據構造的 Tensor
data = [[1, 2, 5], [3, 4, 7]]
tensor3 = torch.tensor(data)
print("\n由數據構造的 Tensor:")
print(tensor3)
print(tensor3.dtype)


零矩陣:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

隨機矩陣:
tensor([[0.9085, 0.2962, 0.0527],
        [0.5110, 0.2204, 0.2008]])

由數據構造的 Tensor:
tensor([[1, 2, 5],
        [3, 4, 7]])
torch.int64


In [13]:
tensor1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
tensor2

tensor([[0.9085, 0.2962, 0.0527],
        [0.5110, 0.2204, 0.2008]])

In [12]:
tensor_add = tensor1 + tensor2
print("\nTensor 相加:", tensor_add)



tensor_multiply = tensor1 * tensor2
print("\nTensor 相乘:", tensor_multiply)


reshape_tensor = tensor3.view(3, 2)
print("\nReshape Tensor:")
print(reshape_tensor)



Tensor 相加: tensor([[0.9085, 0.2962, 0.0527],
        [0.5110, 0.2204, 0.2008]])

Tensor 相乘: tensor([[0., 0., 0.],
        [0., 0., 0.]])

Reshape Tensor:
tensor([[1, 2],
        [5, 3],
        [4, 7]])


In [15]:
import numpy as np


# create 3 numpy array
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,2,2],
              [3,3,3]])
c = np.array([[1,2],
              [3,4],
              [5,6]])

print(f'元素點對點相乘(方法1:np.multiply(a,b)):\n{np.multiply(a,b)}')


元素點對點相乘(方法1:np.multiply(a,b)):
[[ 2  4  6]
 [12 15 18]]


In [16]:
print(f'元素點對點相乘(方法2:a*b):\n{a*b}')

元素點對點相乘(方法2:a*b):
[[ 2  4  6]
 [12 15 18]]


In [18]:
print(f'矩陣相乘(方法1: np.dot(a,c)):\n{np.dot(a,c)}')
print(f'矩陣相乘(方法2: a.dot(c)):\n{a.dot(c)}')
print(f'矩陣相乘(方法3: np.matmul(a,c)):\n{np.matmul(a,c)}')

矩陣相乘(方法1: np.dot(a,c)):
[[22 28]
 [49 64]]
矩陣相乘(方法2: a.dot(c)):
[[22 28]
 [49 64]]
矩陣相乘(方法3: np.matmul(a,c)):
[[22 28]
 [49 64]]
