In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.1.0+cu121'

In [3]:
tsr = torch.randn(4,5)
tsr

tensor([[ 4.1672e-01, -8.7773e-01, -6.2411e-01,  1.2361e-01,  3.9189e-01],
        [-6.5017e-05, -1.1645e-01, -3.8272e-01, -1.7226e+00,  8.8254e-01],
        [ 1.9213e-01,  9.9815e-01,  3.3076e-01, -5.4986e-01, -2.8156e+00],
        [-8.1753e-01,  3.1312e-01,  1.3205e+00,  9.3888e-01,  1.6502e+00]])

In [4]:
m = torch.max(tsr)
m

tensor(1.6502)

In [5]:
m = torch.min(tsr)
m

tensor(-2.8156)

In [7]:
m, idx = torch.max(tsr, 0)
print(m)
print(idx)

tensor([0.4167, 0.9982, 1.3205, 0.9389, 1.6502])
tensor([0, 2, 3, 3, 3])


In [9]:
m, idx = torch.max(tsr, dim=0)
print(m)
print(idx)


tensor([0.4167, 0.9982, 1.3205, 0.9389, 1.6502])
tensor([0, 2, 3, 3, 3])


In [10]:
p =(m, idx)
torch.max(tsr, 0, out=p)



torch.return_types.max_out(
values=tensor([0.4167, 0.9982, 1.3205, 0.9389, 1.6502]),
indices=tensor([0, 2, 3, 3, 3]))