# 1-3 PyTorch 數值型態與基本運算

##  PyTorch 數值型態

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.13.1+cpu'

## 邏輯運算

In [3]:
tsr = torch.randn(4,5)
tsr

tensor([[-2.7260,  0.4783, -0.2906,  0.4397,  0.9391],
        [-2.0382, -1.1389,  0.8143, -0.0686, -0.3839],
        [-0.3889, -1.8110,  0.5220, -0.7152, -1.1229],
        [ 0.6399, -0.0161,  1.9484,  0.6155, -1.3006]])

In [4]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(tsr)
print(m)

tensor(1.9484)


In [5]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(tsr,0)
print(m)
print(idx)

tensor([0.6399, 0.4783, 1.9484, 0.6155, 0.9391])
tensor([3, 0, 3, 3, 0])


In [6]:
# 2-2
m, idx = torch.max(input=tsr,dim=0)
print(m)
print(idx)

tensor([0.6399, 0.4783, 1.9484, 0.6155, 0.9391])
tensor([3, 0, 3, 3, 0])


In [7]:
# 2-5
p = (m,idx)
torch.max(tsr,0,out=p)
print(p[0])
print(p[1])
print(p)

tensor([0.6399, 0.4783, 1.9484, 0.6155, 0.9391])
tensor([3, 0, 3, 3, 0])
(tensor([0.6399, 0.4783, 1.9484, 0.6155, 0.9391]), tensor([3, 0, 3, 3, 0]))


## PyTorch基本運算


### Numpy-Like Implementation 

In [8]:
# 創建一個 2x3 的零矩陣
tensor1 = torch.zeros(2, 3)
print("零矩陣:")
print(tensor1)

# 創建一個 2x3 的隨機矩陣
tensor2 = torch.rand(2, 3)
print("\n隨機矩陣:")
print(tensor2)

# 創建一個直接由數據構造的 Tensor
data = [[1, 2, 5], [3, 4, 7]]
tensor3 = torch.tensor(data)
print("\n由數據構造的 Tensor:")
print(tensor3)
print(tensor3.dtype)


零矩陣:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

隨機矩陣:
tensor([[0.1626, 0.2041, 0.9784],
        [0.9071, 0.6297, 0.7966]])

由數據構造的 Tensor:
tensor([[1, 2, 5],
        [3, 4, 7]])
torch.int64


In [9]:
# Tensor 加法
result_add = tensor2 + tensor3
print("\nTensor 加法結果:")
print(result_add)


# Tensor 加法 (apple 2 apple)
result_muiltiple = tensor2 * tensor3
print("\nTensor 乘法結果:")
print(result_muiltiple)


# Tensor 改變形狀
reshaped = tensor3.view(1, 6)
print("\n重塑後的 Tensor:")
print(reshaped)


Tensor 加法結果:
tensor([[1.1626, 2.2041, 5.9784],
        [3.9071, 4.6297, 7.7966]])

Tensor 乘法結果:
tensor([[0.1626, 0.4083, 4.8919],
        [2.7213, 2.5188, 5.5760]])

重塑後的 Tensor:
tensor([[1, 2, 5, 3, 4, 7]])


### 乘法比較

In [10]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,2,2],
              [3,3,3]])
c = np.array([[1,2],
              [3,4],
              [5,6]])


print(f'元素點對點相乘(方法1:np.multiply(a,b)):\n{np.multiply(a,b)}')
print(f'元素點對點相乘(方法2:a*b):\n{a*b}')

print("")

print(f'矩陣相乘(方法1: np.dot(a,c)):\n{np.dot(a,c)}')
print(f'矩陣相乘(方法2: a.dot(c)):\n{a.dot(c)}')
print(f'矩陣相乘(方法3: np.matmul(a,c)):\n{np.matmul(a,c)}')


元素點對點相乘(方法1:np.multiply(a,b)):
[[ 2  4  6]
 [12 15 18]]
元素點對點相乘(方法2:a*b):
[[ 2  4  6]
 [12 15 18]]

矩陣相乘(方法1: np.dot(a,c)):
[[22 28]
 [49 64]]
矩陣相乘(方法2: a.dot(c)):
[[22 28]
 [49 64]]
矩陣相乘(方法3: np.matmul(a,c)):
[[22 28]
 [49 64]]


看起來```torch.matmul```和```torch.mm```都是進行矩陣內積運算，那```torch.matmul```和```torch.mm```有沒有什麼差異?

```torch.mm```就是一般我們高中數學學的矩陣相乘，```torch.mm(a,b)```的情況，矩陣/向量$a$要能跟矩陣/向量$b$對上<br>
$$a\in R^{(m\times n)}, b\in R^{(n\times k)}，torch.mm(a,b)\in R^{(m\times k)}$$

```torch.matmul```: 除了一般的矩陣內積運算外，他可以達到Python內建廣播運算，叫做broadcasted運算，當兩個tensor的dimension是broadcasted，使用它時候會很有趣。<br>
假設tensor a: $(i\times 1\times n\times m)$ 和 tnesor b: $(k\times m\times p)$<br>
torch.matmul(a,b) = $(i\times k\times n\times p)$

## Torch broadcasted運算

In [11]:
import torch

a = torch.tensor([[[2, 2, 2],
                   [3, 3, 3]]])
print(f'a: {a.shape}')


b = torch.tensor([
    [[[1, 1],
      [1, 1],
      [1, 1]]],
    [[[2, 2],
      [2, 2],
      [2, 2]]],
    [[[3, 3],
      [3, 3],
      [3, 3]]]
])      
print(f'b: {b.shape}')

c = torch.matmul(a, b)
print(f'a * b: {c.shape}')

m = torch.zeros((3, 1, 2, 2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = torch.mm(a[i, :, :], b[j, 0, :, :])


# 確認兩種算法是否一樣
print((c - m).pow(2).sum())



a: torch.Size([1, 2, 3])
b: torch.Size([3, 1, 3, 2])
a * b: torch.Size([3, 1, 2, 2])
tensor(0.)


## Numpy broadcasted運算

In [12]:
import numpy as np

a = np.array([[[2, 2, 2],
               [3, 3, 3]]])
print(f'a: {a.shape}')

b = np.array([
    [[[1, 1],
      [1, 1],
      [1, 1]]],
    [[[2, 2],
      [2, 2],
      [2, 2]]],
    [[[3, 3],
      [3, 3],
      [3, 3]]]
])      
print(f'b: {b.shape}')

c = np.matmul(a, b)
print(f'a * b: {c.shape}')

m = np.zeros((3, 1, 2, 2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = np.matmul(a[i, :, :], b[j, 0, :, :])


# 確認兩種算法是否一樣
print(((c - m)**2).sum())



a: (1, 2, 3)
b: (3, 1, 3, 2)
a * b: (3, 1, 2, 2)
0.0


## 效能比較 torch array vs numpy array
### 利用broadcasted運算特性可以節省for loop的時間。

In [13]:
import time
import torch

# Define a function to format elapsed time
def format_time(start_time):
    elapsed_time = time.time() - start_time
    return f'{elapsed_time:.4f} seconds'  # Formats time to 4 decimal places

# Create random tensors a and b
a = torch.rand((100, 5, 10))
b = torch.rand((200, 1, 10, 20))
print(f'a: {a.shape}')
print(f'b: {b.shape}')

# Matrix multiplication using torch.matmul
start_time = time.time()
c = torch.matmul(a, b)
print(f'a * b: {c.shape}')
process_time_matmul = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

# Manual matrix multiplication using for loops
start_time = time.time()
m = torch.zeros((200, 100, 5, 20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = torch.mm(a[i, :, :], b[j, 0, :, :])
process_time_loops = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

print(f"速度差異 {process_time_loops/process_time_matmul:.2f} 倍")
# Calculate and print the absolute sum of differences
difference = (c - m).abs().sum()
print(f'差異總和: {difference}')



a: torch.Size([100, 5, 10])
b: torch.Size([200, 1, 10, 20])
a * b: torch.Size([200, 100, 5, 20])
計算時間: 0.0660 seconds
計算時間: 2.4513 seconds
速度差異 37.14 倍
差異總和: 0.0


In [14]:
import time
import torch

# Define a function to format elapsed time
def format_time(start_time):
    elapsed_time = time.time() - start_time
    return f'{elapsed_time:.4f} seconds'  # Formats time to 4 decimal places

# Create random tensors a and b
a=np.random.rand(100,5,10)
b=np.random.rand(200,1,10,20)
print(f'a: {a.shape}')
print(f'b: {b.shape}')

# Matrix multiplication using torch.matmul
start_time = time.time()
c=np.matmul(a,b)
print(f'a * b: {c.shape}')
process_time_matmul = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

# Manual matrix multiplication using for loops
start_time = time.time()
m=np.zeros((200,100,5,20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j,i,:,:] = np.matmul(a[i,:,:], b[j,0,:,:])
process_time_loops = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

print(f"速度差異 {process_time_loops/process_time_matmul:.2f} 倍")
# Calculate and print the absolute sum of differences
difference = np.abs((c - m)).sum()
print(f'差異總和: {difference}')


a: (100, 5, 10)
b: (200, 1, 10, 20)
a * b: (200, 100, 5, 20)
計算時間: 0.0311 seconds
計算時間: 0.2624 seconds
速度差異 8.44 倍
差異總和: 0.0


### 線性代數函數庫 (Torch vs Numpy)

In [15]:
import numpy as np
import torch

a_np = np.array([[6.0, 2.0],
                 [4.0, 5.0]])
a_torch = torch.tensor(a_np)


print("numpy array\n", a_np)

print("torch array\n", a_torch)


numpy array
 [[6. 2.]
 [4. 5.]]
torch array
 tensor([[6., 2.],
        [4., 5.]], dtype=torch.float64)


In [16]:
# normalization
print(np.linalg.norm(a_np))
print(torch.linalg.norm(a_torch))

9.0
tensor(9., dtype=torch.float64)


In [17]:
#
print(np.linalg.inv(a_np))
print(torch.linalg.inv(a_torch))

[[ 0.22727273 -0.09090909]
 [-0.18181818  0.27272727]]
tensor([[ 0.2273, -0.0909],
        [-0.1818,  0.2727]], dtype=torch.float64)
