# PyTorch 數值型態與基本運算



In [22]:
import torch
import numpy as np

In [23]:
torch.__version__

'1.13.1+cpu'

In [24]:
if torch.cuda.is_available():
    # Get the number of available GPUs
    num_gpus = torch.cuda.device_count()
    
    # Get the name of the current GPU
    current_gpu_name = torch.cuda.get_device_name(0)  # Assuming you have at least one GPU
    
    print(f"Number of available GPUs: {num_gpus}")
    print(f"Current GPU name: {current_gpu_name}")
       
    # Now, operations will be performed on the GPU by default if available
    cuda0 = torch.device('cuda:0')
    tsr = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float64, device=cuda0)
else:
    print("No GPU available. Using CPU.")

cuda0 = torch.device('cuda', 0)
cuda1 = torch.device('cuda', 1)
cpu = torch.device('cpu')

No GPU available. Using CPU.


## tensor 創建

In [25]:
tsr = torch.tensor([[1,2],[3,4],[5,6]]); tsr

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [26]:
# 創建一個 2x3 的零矩陣
tensor1 = torch.zeros(2, 3)
print("零矩陣:")
print(tensor1)

# 創建一個 2x3 的隨機矩陣
tensor2 = torch.rand(2, 3)
print("\n隨機矩陣:")
print(tensor2)

# 創建一個直接由數據構造的 Tensor
data = [[1, 2, 5], [3, 4, 7]]
tensor3 = torch.tensor(data)
print("\n由數據構造的 Tensor:")
print(tensor3)
print(tensor3.dtype)

零矩陣:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

隨機矩陣:
tensor([[0.1833, 0.4602, 0.2281],
        [0.7871, 0.1627, 0.1672]])

由數據構造的 Tensor:
tensor([[1, 2, 5],
        [3, 4, 7]])
torch.int64


## tensor data type


![**tensor data type**](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*CHitOyDsG5fXhR80cAT3Ag.png)

In [27]:
tsr = torch.tensor([[1,2],[3,4]], dtype=torch.float64); tsr

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [28]:
# Create a tensor with a single element, 1, using the default tensor type (usually FloatTensor)
tmp_tensor = torch.tensor([1])

# Create a FloatTensor (32-bit floating point) with a single element, 1.01
float_32 = torch.FloatTensor([1.01]) # 32 bits

# Create a DoubleTensor (64-bit floating point) with a single element, 1.01
float_64 = torch.DoubleTensor([1.01]) # 64 bits

# Create an IntTensor (32-bit integer) with a single element, 1
int_32 = torch.IntTensor([1]) # 32 bits

# Create a LongTensor (64-bit integer) with a single element, 1
int_64 = torch.LongTensor([1]) # 64 bits


In [29]:
names = ['float_32', 'float_64', 'int_32', 'int_64']
for i, tmp1 in enumerate([float_32, float_64, int_32, int_64]):
    for j, tmp2 in enumerate([float_32, float_64, int_32, int_64]):
        # print('{} + {}:\t{}'.format(names[i], names[j], (tmp1+tmp2).dtype))
        # print('{} * {}:\t{}'.format(names[i], names[j], (tmp1*tmp2).dtype))
        # print('{} / {}:\t{}'.format(names[i], names[j], (tmp1/tmp2).dtype))


        print(f"{names[i]} + {names[j]}:\t{(tmp1+tmp2).dtype}")
        print(f"{names[i]} * {names[j]}:\t{(tmp1+tmp2).dtype}")
        print(f"{names[i]} / {names[j]}:\t{(tmp1+tmp2).dtype}")

        print("------")

float_32 + float_32:	torch.float32
float_32 * float_32:	torch.float32
float_32 / float_32:	torch.float32
------
float_32 + float_64:	torch.float64
float_32 * float_64:	torch.float64
float_32 / float_64:	torch.float64
------
float_32 + int_32:	torch.float32
float_32 * int_32:	torch.float32
float_32 / int_32:	torch.float32
------
float_32 + int_64:	torch.float32
float_32 * int_64:	torch.float32
float_32 / int_64:	torch.float32
------
float_64 + float_32:	torch.float64
float_64 * float_32:	torch.float64
float_64 / float_32:	torch.float64
------
float_64 + float_64:	torch.float64
float_64 * float_64:	torch.float64
float_64 / float_64:	torch.float64
------
float_64 + int_32:	torch.float64
float_64 * int_32:	torch.float64
float_64 / int_32:	torch.float64
------
float_64 + int_64:	torch.float64
float_64 * int_64:	torch.float64
float_64 / int_64:	torch.float64
------
int_32 + float_32:	torch.float32
int_32 * float_32:	torch.float32
int_32 / float_32:	torch.float32
------
int_32 + float_64:	tor

### tensor <-----> numpy 

In [30]:
# tensor transfer to numpy
tsr2numpy = tsr.numpy()
print('numpy', tsr2numpy)
print('type:', type(tsr2numpy))


numpy [[1. 2.]
 [3. 4.]]
type: <class 'numpy.ndarray'>


In [31]:
# numpy transfer to tensor

'''
torch.Tensor
torch.tensor
torch.as_tensor
torch.from_numpy

'''
arr = np.array([[1,2,3],[4,5,6]])

#1 sol
arr2tsr_1 = torch.tensor(arr)
print("tensor:", arr2tsr_1)
print("dtype:", arr2tsr_1.dtype)

#2 sol
arr2tsr_2 = torch.Tensor(arr)
print("tensor:", arr2tsr_2)
print("dtype:", arr2tsr_2.dtype)

#3 sol
arr2tsr_3 = torch.as_tensor(arr)
print("tensor:", arr2tsr_3)
print("dtype:", arr2tsr_3.dtype)

#4 sol
arr2tsr_4 = torch.from_numpy(arr)
print("tensor:", arr2tsr_4)
print("dtype:", arr2tsr_4.dtype)




tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32
tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
dtype: torch.float32
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32


## PyTorch Tensor 和資料型態

#### 可微分Tensor的資料型態限制 :
不可隨意改變資料型態：當Tensor被用作模型的參數，且是可微分的（參與反向傳播計算），其資料型態不能隨意改變。

#### PyTorch模型參數的預設資料型態 :
預設為Float32：PyTorch中模型參數的預設資料型態是32位浮點數（Float32）。這提供了足夠的精度，同時節省記憶體和計算時間。

#### Numpy預設資料型態與轉換注意事項 :
Numpy預設為Float64：Numpy的預設浮點數資料型態是Double（Float64），這與PyTorch的預設不同。
轉換時的注意事項：在將Numpy陣列轉換成PyTorch Tensor時，需要特別注意這一點。直接轉換可能導致效能降低或不必要的資源消耗。



In [32]:
import torch
import torchvision
mobilenet_v2 = torchvision.models.mobilenet_v2(pretrained=True)

mobilenet_v2.eval() 

dummy_input = torch.randn(1, 3, 224, 224)
print("模型預測前", dummy_input.dtype)

tmp = mobilenet_v2(dummy_input)

print("模型預測前", tmp.dtype)
print('---------')

C:\Users\xdxd2\AppData\Roaming\Python\Python310\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\xdxd2\AppData\Roaming\Python\Python310\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


模型預測前 torch.float32
模型預測前 torch.float32
---------


如果我們沒有注意到輸入的資料格式，直接把numpy的array轉成torch tensor輸入到模型內。

In [33]:
import cv2
import numpy as np
img = cv2.imread('cat.jpg')
img = cv2.resize(img, (224,224))

# numpy array
img = np.array(img)/255
print("- numpy array")
print(img.shape)
print(img.dtype)
print("")

# torch array
img = torch.tensor(img)

'''
permute: 
2 moves the original third dimension (color channels) to the first position.
0 moves the original first dimension (height) to the second position.
1 moves the original second dimension (width) to the third position.
'''

img = img.permute(2, 0, 1)
print("- torch tensor")
print(img.shape)
print(img.dtype)
print("")


# change dimension
img=img.unsqueeze(0)
print("- expand dimension")
print(img.shape)
print(img.dtype)


- numpy array
(224, 224, 3)
float64

- torch tensor
torch.Size([3, 224, 224])
torch.float64

- expand dimension
torch.Size([1, 3, 224, 224])
torch.float64


In [34]:
## float64 送進模型會報錯

tmp = mobilenet_v2(img)

RuntimeError: expected scalar type Double but found Float

避免這類型的出錯，盡量在numpy array或是image型態轉成torch tensor時候，就指定他是```torch.FloatTensor```。

In [35]:
import cv2
import numpy as np
import torch

img = cv2.imread('cat.jpg')
img = cv2.resize(img, (224,224))
img = np.array(img)/255


# # 轉型 float32
img = torch.FloatTensor(img)

img = img.permute(2, 0, 1)

img=img.unsqueeze(0)
tmp = mobilenet_v2(img)
print(tmp.shape)



torch.Size([1, 1000])
