# 1-3 PyTorch 數值型態與基本運算

##  PyTorch 數值型態

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.13.1+cpu'

## 邏輯運算

In [4]:
tsr = torch.randn(4,5)
tsr

tensor([[ 0.5544,  0.3945,  0.7134, -0.9825,  2.3436],
        [ 1.5518,  0.3083,  0.5637, -1.1906,  0.8133],
        [ 0.6354,  1.1493,  0.2742,  0.6630,  0.4845],
        [-1.5488, -0.0314,  1.7406,  0.3260, -0.6287]])

In [5]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(tsr)
print(m)

tensor(2.3436)


In [6]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(tsr,0)
print(m)
print(idx)

tensor([1.5518, 1.1493, 1.7406, 0.6630, 2.3436])
tensor([1, 2, 3, 2, 0])


In [7]:
# 2-2
m, idx = torch.max(input=tsr,dim=0)
print(m)
print(idx)

tensor([1.5518, 1.1493, 1.7406, 0.6630, 2.3436])
tensor([1, 2, 3, 2, 0])


In [8]:
# 2-5
p = (m,idx)
torch.max(tsr,0,out=p)
print(p[0])
print(p[1])
print(p)

tensor([1.5518, 1.1493, 1.7406, 0.6630, 2.3436])
tensor([1, 2, 3, 2, 0])
(tensor([1.5518, 1.1493, 1.7406, 0.6630, 2.3436]), tensor([1, 2, 3, 2, 0]))


## PyTorch基本運算


### Numpy-Like Implementation 

In [9]:
# 創建一個 2x3 的零矩陣
tensor1 = torch.zeros(2, 3)
print("零矩陣:")
print(tensor1)

# 創建一個 2x3 的隨機矩陣
tensor2 = torch.rand(2, 3)
print("\n隨機矩陣:")
print(tensor2)

# 創建一個直接由數據構造的 Tensor
data = [[1, 2, 5], [3, 4, 7]]
tensor3 = torch.tensor(data)
print("\n由數據構造的 Tensor:")
print(tensor3)
print(tensor3.dtype)


零矩陣:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

隨機矩陣:
tensor([[0.3339, 0.6048, 0.4548],
        [0.2829, 0.2104, 0.6105]])

由數據構造的 Tensor:
tensor([[1, 2, 5],
        [3, 4, 7]])
torch.int64


In [10]:
# Tensor 加法
result_add = tensor2 + tensor3
print("\nTensor 加法結果:")
print(result_add)


# Tensor 加法 (apple 2 apple)
result_muiltiple = tensor2 * tensor3
print("\nTensor 乘法結果:")
print(result_muiltiple)


# Tensor 改變形狀
reshaped = tensor3.view(1, 6)
print("\n重塑後的 Tensor:")
print(reshaped)


Tensor 加法結果:
tensor([[1.3339, 2.6048, 5.4548],
        [3.2829, 4.2104, 7.6105]])

Tensor 乘法結果:
tensor([[0.3339, 1.2097, 2.2739],
        [0.8486, 0.8415, 4.2738]])

重塑後的 Tensor:
tensor([[1, 2, 5, 3, 4, 7]])


### 乘法比較

In [11]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,2,2],
              [3,3,3]])
c = np.array([[1,2],
              [3,4],
              [5,6]])


print(f'元素點對點相乘(方法1:np.multiply(a,b)):\n{np.multiply(a,b)}')
print(f'元素點對點相乘(方法2:a*b):\n{a*b}')

print("")

print(f'矩陣相乘(方法1: np.dot(a,c)):\n{np.dot(a,c)}')
print(f'矩陣相乘(方法2: a.dot(c)):\n{a.dot(c)}')
print(f'矩陣相乘(方法3: np.matmul(a,c)):\n{np.matmul(a,c)}')


元素點對點相乘(方法1:np.multiply(a,b)):
[[ 2  4  6]
 [12 15 18]]
元素點對點相乘(方法2:a*b):
[[ 2  4  6]
 [12 15 18]]

矩陣相乘(方法1: np.dot(a,c)):
[[22 28]
 [49 64]]
矩陣相乘(方法2: a.dot(c)):
[[22 28]
 [49 64]]
矩陣相乘(方法3: np.matmul(a,c)):
[[22 28]
 [49 64]]


# torch.matmul 與 torch.mm 的差異

在 PyTorch 中，`torch.matmul` 和 `torch.mm` 都用於執行矩陣內積運算，但它們在功能和應用場景上存在一定的差異。

## torch.mm

- `torch.mm` 執行的是標準的矩陣乘法運算。
- 用法: `torch.mm(a, b)`，其中 `a` 和 `b` 是矩陣。
- 約束: 矩陣 `a` 的列數必須與矩陣 `b` 的行數相同。
- 維度要求: 如果矩陣 `a` 是 \(m \times n\)，矩陣 `b` 是 \(n \times k\)，則結果矩陣將是 \(m \times k\)。
- 例子: 若 `a` ∈ \(R^{m \times n}\) 且 `b` ∈ \(R^{n \times k}\)，則 `torch.mm(a, b)` ∈ \(R^{m \times k}\)。

## torch.matmul

- `torch.matmul` 提供了更廣泛的矩陣乘法運算，包括標準矩陣乘法、點乘以及維度廣播。
- 廣播運算: `torch.matmul` 支持廣播運算，能夠自動擴展維度以適應矩陣運算的需求。
- 維度要求: 對於高維張量，`torch.matmul` 可以處理形如 \(i \times 1 \times n \times m\) 和 \(k \times m \times p\) 的張量，並輸出形為 \(i \times k \times n \times p\) 的張量。
- 靈活性: `torch.matmul` 在處理不同維度張量時提供了更大的靈活性和應用範圍。

## 總結

雖然 `torch.mm` 和 `torch.matmul` 都可用於矩陣乘法，但 `torch.matmul` 提供了更廣泛的功能，特別是在處理高維數據和需要廣播功能的場景中。選擇使用哪一個函數，應根據具體的應用需求和矩陣的維度來決定。


## Torch broadcasted運算

In [12]:
import torch

a = torch.tensor([[[2, 2, 2],
                   [3, 3, 3]]])
print(f'a: {a.shape}')


b = torch.tensor([
    [[[1, 1],
      [1, 1],
      [1, 1]]],
    [[[2, 2],
      [2, 2],
      [2, 2]]],
    [[[3, 3],
      [3, 3],
      [3, 3]]]
])      
print(f'b: {b.shape}')

c = torch.matmul(a, b)
print(f'a * b: {c.shape}')

m = torch.zeros((3, 1, 2, 2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = torch.mm(a[i, :, :], b[j, 0, :, :])


# 確認兩種算法是否一樣
print((c - m).pow(2).sum())



a: torch.Size([1, 2, 3])
b: torch.Size([3, 1, 3, 2])
a * b: torch.Size([3, 1, 2, 2])
tensor(0.)


## Numpy broadcasted運算

In [13]:
import numpy as np

a = np.array([[[2, 2, 2],
               [3, 3, 3]]])
print(f'a: {a.shape}')

b = np.array([
    [[[1, 1],
      [1, 1],
      [1, 1]]],
    [[[2, 2],
      [2, 2],
      [2, 2]]],
    [[[3, 3],
      [3, 3],
      [3, 3]]]
])      
print(f'b: {b.shape}')

c = np.matmul(a, b)
print(f'a * b: {c.shape}')

m = np.zeros((3, 1, 2, 2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = np.matmul(a[i, :, :], b[j, 0, :, :])


# 確認兩種算法是否一樣
print(((c - m)**2).sum())



a: (1, 2, 3)
b: (3, 1, 3, 2)
a * b: (3, 1, 2, 2)
0.0


## 效能比較 torch array vs numpy array
### 利用broadcasted運算特性可以節省for loop的時間。

In [14]:
import time
import torch

# Define a function to format elapsed time
def format_time(start_time):
    elapsed_time = time.time() - start_time
    return f'{elapsed_time:.4f} seconds'  # Formats time to 4 decimal places

# Create random tensors a and b
a = torch.rand((100, 5, 10))
b = torch.rand((200, 1, 10, 20))
print(f'a: {a.shape}')
print(f'b: {b.shape}')

# Matrix multiplication using torch.matmul
start_time = time.time()
c = torch.matmul(a, b)
print(f'a * b: {c.shape}')
process_time_matmul = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

# Manual matrix multiplication using for loops
start_time = time.time()
m = torch.zeros((200, 100, 5, 20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = torch.mm(a[i, :, :], b[j, 0, :, :])
process_time_loops = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

print(f"速度差異 {process_time_loops/process_time_matmul:.2f} 倍")
# Calculate and print the absolute sum of differences
difference = (c - m).abs().sum()
print(f'差異總和: {difference}')



a: torch.Size([100, 5, 10])
b: torch.Size([200, 1, 10, 20])
a * b: torch.Size([200, 100, 5, 20])
計算時間: 0.0437 seconds


計算時間: 1.2920 seconds
速度差異 29.60 倍
差異總和: 0.0


In [15]:
import time
import torch

# Define a function to format elapsed time
def format_time(start_time):
    elapsed_time = time.time() - start_time
    return f'{elapsed_time:.4f} seconds'  # Formats time to 4 decimal places

# Create random tensors a and b
a=np.random.rand(100,5,10)
b=np.random.rand(200,1,10,20)
print(f'a: {a.shape}')
print(f'b: {b.shape}')

# Matrix multiplication using torch.matmul
start_time = time.time()
c=np.matmul(a,b)
print(f'a * b: {c.shape}')
process_time_matmul = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

# Manual matrix multiplication using for loops
start_time = time.time()
m=np.zeros((200,100,5,20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j,i,:,:] = np.matmul(a[i,:,:], b[j,0,:,:])
process_time_loops = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

print(f"速度差異 {process_time_loops/process_time_matmul:.2f} 倍")
# Calculate and print the absolute sum of differences
difference = np.abs((c - m)).sum()
print(f'差異總和: {difference}')


a: (100, 5, 10)
b: (200, 1, 10, 20)
a * b: (200, 100, 5, 20)
計算時間: 0.0161 seconds
計算時間: 0.1454 seconds
速度差異 9.00 倍
差異總和: 0.0


# 線性代數運算操作比較 (Torch vs Numpy)



### 常見線性代數操作比較 (Torch vs Numpy)

In [16]:
import numpy as np
import torch

# 給定的 NumPy 陣列和 PyTorch 張量
a_np = np.array([[6.0, 2.0],
                 [4.0, 5.0]])
a_torch = torch.tensor(a_np, dtype=torch.float)

print(a_np)

print(a_torch)


[[6. 2.]
 [4. 5.]]
tensor([[6., 2.],
        [4., 5.]])


In [17]:
# 1. 矩陣轉置
a_np_transposed = a_np.T
a_torch_transposed = a_torch.t()

print("NumPy Transposed:\n", a_np_transposed)
print("PyTorch Transposed:\n", a_torch_transposed)



NumPy Transposed:
 [[6. 4.]
 [2. 5.]]
PyTorch Transposed:
 tensor([[6., 4.],
        [2., 5.]])


In [18]:
# 2. 矩陣乘法 (以自身為例)
a_np_mult = np.dot(a_np, a_np_transposed)
a_torch_mult = torch.mm(a_torch, a_torch_transposed)

print("NumPy Matrix Multiplication:\n", a_np_mult)
print("PyTorch Matrix Multiplication:\n", a_torch_mult)

NumPy Matrix Multiplication:
 [[40. 34.]
 [34. 41.]]
PyTorch Matrix Multiplication:
 tensor([[40., 34.],
        [34., 41.]])


In [19]:
# 3. 求逆矩陣 (注意: 僅當矩陣可逆時有效)
a_np_inverse = np.linalg.inv(a_np)
a_torch_inverse = torch.inverse(a_torch)

print("NumPy Inverse:\n", a_np_inverse)
print("PyTorch Inverse:\n", a_torch_inverse)



NumPy Inverse:
 [[ 0.22727273 -0.09090909]
 [-0.18181818  0.27272727]]
PyTorch Inverse:
 tensor([[ 0.2273, -0.0909],
        [-0.1818,  0.2727]])


In [20]:
# 4. 行列式計算
a_np_det = np.linalg.det(a_np)
a_torch_det = torch.det(a_torch)

print("NumPy Determinant:", a_np_det)
print("PyTorch Determinant:", a_torch_det)

NumPy Determinant: 22.000000000000004
PyTorch Determinant: tensor(22.)


## 向量範數計算類型

在線性代數中，「範數」是用於衡量向量大小的一種重要概念。本指南旨在為程式設計初學者提供關於不同範數計算方法的清晰解釋，包括 1-範數、2-範數、無窮範數，以及 p-範數。以下是各種範數的定義及其計算方法。

## 1. 1-範數 (L1 Norm)

1-範數，也稱為「曼哈頓距離」，是向量中各元素絕對值的總和。

- **計算公式：**

  $$
  \|x\|_1 = \sum_{i=1}^{n} |x_i|
  $$

## 2. 2-範數 (L2 Norm)

2-範數，亦即「歐幾里得範數」，是向量中各元素平方和的平方根。

- **計算公式：**

  $$
  \|x\|_2 = \sqrt{\sum_{i=1}^{n} x_i^2}
  $$

## 3. 無窮範數 (L∞ Norm)

無窮範數是向量中的最大絕對值。

- **計算公式：**

  $$
  \|x\|_\infty = \max_i |x_i|
  $$

## 4. p-範數 (Lp Norm)

p-範數是一個泛化的範數形式，適用於當 \(p \geq 1\) 時。

- **計算公式：**

  $$
  \|x\|_p = \left(\sum_{i=1}^{n} |x_i|^p\right)^{\frac{1}{p}}
  $$

範數在數學、物理學和工程學中扮演著關鍵角色。在機器學習領域，L1範數有助於促進模型的稀疏性，而L2範數常用於防止過擬合，也就是所謂的「L2正則化」。根據您的具體需求選擇合適的範數來進行計算。

希望本指南能夠幫助您更好地理解和計算各種向量範數。


In [21]:
import numpy as np
import torch

# 給定的 NumPy 陣列和 PyTorch 張量
a_np = np.array([[6.0, 2.0],
                 [4.0, 5.0]])
a_torch = torch.tensor(a_np, dtype=torch.float)

print(a_np)

print(a_torch)

[[6. 2.]
 [4. 5.]]
tensor([[6., 2.],
        [4., 5.]])


In [27]:
# NumPy 計算範數
# 在 NumPy 的 np.linalg.norm 函數中，指定 ord=1 會計算矩陣的列和的最大值（即按列求絕對值之和的最大值）
l1_norm_np = np.linalg.norm(a_np, ord=1)  # L1範數
l2_norm_np = np.linalg.norm(a_np)  # L2範數，預設為ord=2

# PyTorch 計算範數
l1_norm_torch = torch.norm(a_torch, p=1)  # L1範數
l2_norm_torch = torch.norm(a_torch)  # L2範數，預設為p=2

print("NumPy L1範數:", l1_norm_np)
print("NumPy L2範數:", l2_norm_np)
print("PyTorch L1範數:", l1_norm_torch)
print("PyTorch L2範數:", l2_norm_torch)

NumPy L1範數: 10.0
NumPy L2範數: 9.0
PyTorch L1範數: tensor(17., dtype=torch.float64)
PyTorch L2範數: tensor(9., dtype=torch.float64)


In [28]:
# 使用 NumPy 計算所有元素的絕對值之和
l1_norm_np = np.sum(np.abs(a_np))

# 使用 PyTorch 計算所有元素的絕對值之和
l1_norm_torch = torch.sum(torch.abs(a_torch))

print("NumPy L1範數（所有元素絕對值之和）:", l1_norm_np)
print("PyTorch L1範數（所有元素絕對值之和）:", l1_norm_torch.item())  # 使用 .item() 將單元素張量轉換為Python數值


NumPy L1範數（所有元素絕對值之和）: 17.0
PyTorch L1範數（所有元素絕對值之和）: 17.0
