In [9]:
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

In [10]:
dataset_transform = transforms.Compose([transforms.ToTensor()])

# train_set = torchvision.datasets.CIFAR10(root="./dataset", train=True, transform=dataset_transform, download=True)
test_data = torchvision.datasets.CIFAR10(root="./dataset", train=False, transform=dataset_transform, download=True)
test_loader = DataLoader(dataset=test_data, batch_size=64, shuffle=True, num_workers=0, drop_last=False)

# # 測試數據集中 第一張圖片及 target
# img, target = test_data[0]
# print(img.shape)
# print(target)


Files already downloaded and verified


In [11]:
# 測試數據集中第一張圖片及target
img, target = test_data[0]
print(img.shape)
print(target)

writter = SummaryWriter("tb_dataloader")

for epoch in range(2):
    step = 0
    for data in test_loader:
        imgs, targets = data
        print(imgs.shape)
        print(targets)

        writter.add_images("epoch: {epoch}", imgs, step)
        step = step + 1

writter.close()




torch.Size([3, 32, 32])
3
torch.Size([64, 3, 32, 32])
tensor([3, 7, 7, 9, 5, 6, 0, 2, 0, 4, 7, 7, 1, 6, 8, 7, 5, 4, 1, 0, 4, 8, 3, 8,
        7, 2, 5, 4, 8, 3, 0, 2, 9, 9, 7, 1, 2, 6, 1, 9, 0, 9, 2, 9, 7, 7, 7, 0,
        3, 6, 0, 7, 4, 7, 7, 1, 5, 5, 9, 8, 9, 6, 5, 8])
torch.Size([64, 3, 32, 32])
tensor([5, 8, 9, 1, 1, 0, 5, 1, 4, 4, 3, 1, 3, 1, 0, 9, 4, 7, 3, 8, 2, 7, 7, 8,
        9, 2, 1, 8, 2, 5, 9, 4, 7, 6, 4, 2, 9, 8, 3, 9, 9, 9, 7, 7, 5, 0, 5, 1,
        7, 2, 4, 8, 4, 2, 9, 6, 2, 1, 7, 8, 0, 7, 3, 7])
torch.Size([64, 3, 32, 32])
tensor([7, 0, 5, 8, 5, 6, 3, 1, 6, 3, 5, 1, 0, 8, 6, 3, 0, 1, 7, 0, 5, 0, 6, 1,
        1, 9, 9, 1, 3, 0, 9, 0, 0, 4, 9, 7, 5, 5, 3, 9, 0, 1, 0, 7, 8, 5, 8, 3,
        2, 2, 3, 5, 2, 5, 8, 8, 7, 9, 8, 4, 7, 5, 6, 3])
torch.Size([64, 3, 32, 32])
tensor([9, 3, 0, 2, 3, 9, 8, 2, 0, 2, 9, 4, 8, 5, 7, 9, 3, 7, 3, 8, 0, 8, 1, 3,
        4, 9, 2, 8, 5, 7, 3, 6, 0, 1, 5, 4, 0, 3, 4, 6, 2, 3, 3, 2, 6, 4, 8, 8,
        9, 8, 7, 1, 9, 3, 1, 5, 3, 2, 0, 7, 6, 8, 4